### ISSUE TITLE
US2 - Visual Map

### ISSUE THREAD

**Issue by dennisliang01** [dennisliang01/zooseeker#2]

**Comment by dennisliang01** [comment]
- US 2-1 https://github.com/dennisliang01/zooseeker/issues/4
- US 2-2 https://github.com/dennisliang01/zooseeker/issues/5
- US 2-3 https://github.com/dennisliang01/zooseeker/issues/6
- US 2-4 https://github.com/dennisliang01/zooseeker/issues/8
- US 2-5 https://github.com/dennisliang01/zooseeker/issues/9
- US 2-6 https://github.com/dennisliang01/zooseeker/issues/11
- US 2-8 https://github.com/dennisliang01/zooseeker/issues/14
- US 2-9 https://github.com/dennisliang01/zooseeker/issues/18
- US 2-11 https://github.com/dennisliang01/zooseeker/issues/35
- US 2-12 https://github.com/dennisliang01/zooseeker/issues/36
- US 2-13 https://github.com/dennisliang01/zooseeker/issues/37
- US 2-13 https://github.com/dennisliang01/zooseeker/issues/40
- US 2-13 https://github.com/dennisliang01/zooseeker/issues/41
- US 2-7 https://github.com/dennisliang01/zooseeker/issues/13

**Comment by chuongnguyen26** [comment]
Visual map was added to the US2-Revamp-Map branch
