### ISSUE TITLE
US13 - Map: Exhibit Detail

### ISSUE THREAD

**Issue by juhengwu** [dennisliang01/zooseeker#38]
User story for the implementation and refinement of the exhibit detail screen

**Comment by B3DAN** [comment]
- US 13-1 https://github.com/dennisliang01/zooseeker/issues/47
- US 13-3 https://github.com/dennisliang01/zooseeker/issues/49
- US 13-4 https://github.com/dennisliang01/zooseeker/issues/50
- Us 13-6 https://github.com/dennisliang01/zooseeker/issues/57
- US 13-5 https://github.com/dennisliang01/zooseeker/issues/51
- US 13-2 https://github.com/dennisliang01/zooseeker/issues/48
