### ISSUE TITLE
US12 - Exhibit Plan Creation

### ISSUE THREAD

**Issue by juhengwu** [dennisliang01/zooseeker#39]

**Comment by B3DAN** [comment]
- US 12-1 https://github.com/dennisliang01/zooseeker/issues/52
- US 12-2 https://github.com/dennisliang01/zooseeker/issues/53
- US 12-3 https://github.com/dennisliang01/zooseeker/issues/54
- US 12-4 https://github.com/dennisliang01/zooseeker/issues/55
- US 12-5 https://github.com/dennisliang01/zooseeker/issues/56
